{
 "title": "ClickHouse Performance Monitor",
 "description": "ClickHouse Performance Monitor",
 "tags": [
  "clickhouse",
  "performance"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5m" },
   { "name": "type", "label": "type", "query": "1,2,3,4" },
   { "name": "top", "label": "top elements", "query": "5,10,15,20,25,30" },
   {
    "name": "user",
    "label": "initial user",
    "query": "select distinct initial_user from system.query_log where event_date >= today()-3 and event_time > toDateTime(today()-3)"
   },
   { "name": "query_type", "label": "query type", "query": "all,select,insert" }
  ]
 },
 "panels": [
  {
   "title": "CK UP Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "last_time",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uptime()\n",
     "rawQuery": "SELECT uptime()",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Part Info Base",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "delete_ttl_info_max",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database,\n    table,\n    partition,\n    name,\n    part_type,\n    rows,\n    bytes_on_disk,\n    data_compressed_bytes\nFROM $table\n\nWHERE database!='system'\n",
     "rawQuery": "SELECT\n    database,\n    table,\n    partition,\n    name,\n    part_type,\n    rows,\n    bytes_on_disk,\n    data_compressed_bytes\nFROM system.parts\n\nWHERE database!='system'",
     "round": "0s",
     "table": "parts"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "database": "system",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    name as Name,\n    path as Path,\n    free_space as Free,\n    total_space as Total,\n    1 - free_space/total_space as Used\nFROM $table",
     "rawQuery": "SELECT\n    name as Name,\n    path as Path,\n    free_space as Free,\n    total_space as Total,\n    1 - free_space/total_space as Used\nFROM system.disks",
     "round": "0s",
     "table": "disks"
    }
   ]
  },
  {
   "title": "Replica Info Base",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    value as ReplicasMaxAbsoluteDelay\nFROM $table\n\nWHERE metric='ReplicasMaxAbsoluteDelay'\n\n",
     "rawQuery": "SELECT\n    value as ReplicasMaxAbsoluteDelay\nFROM system.asynchronous_metrics\n\nWHERE metric='ReplicasMaxAbsoluteDelay'",
     "round": "0s",
     "table": "asynchronous_metrics"
    },
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    value as ReplicasMaxRelativeDelay\nFROM $table\n\nWHERE metric='ReplicasMaxRelativeDelay'\n",
     "rawQuery": "SELECT\n    value as ReplicasMaxRelativeDelay\nFROM system.asynchronous_metrics\n\nWHERE metric='ReplicasMaxRelativeDelay'",
     "round": "0s",
     "table": "asynchronous_metrics"
    },
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    value as ReplicasMaxQueueSize\nFROM $table\n\nWHERE metric='ReplicasMaxQueueSize'\n",
     "rawQuery": "SELECT\n    value as ReplicasMaxQueueSize\nFROM system.asynchronous_metrics\n\nWHERE metric='ReplicasMaxQueueSize'",
     "round": "0s",
     "table": "asynchronous_metrics"
    }
   ]
  },
  {
   "title": "Table Info Basic",
   "type": "table",
   "description": "表的列数",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "metadata_modification_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database as DatabaseName,\n    name as TableName,\n    total_rows as TotalRows,\n    total_bytes as TotalBytes\nFROM $table\n\nWHERE database !='system'\n",
     "rawQuery": "SELECT\n    database as DatabaseName,\n    name as TableName,\n    total_rows as TotalRows,\n    total_bytes as TotalBytes\nFROM system.tables\n\nWHERE database !='system'",
     "round": "0s",
     "table": "tables"
    },
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database as DatabaseName,\n    table as TableName,\n    count(1) as ColumnCnt\nFROM $table\nWHERE database!='system'\nGROUP BY DatabaseName, TableName",
     "rawQuery": "SELECT\n    database as DatabaseName,\n    table as TableName,\n    count(1) as ColumnCnt\nFROM system.columns\nWHERE database!='system'\nGROUP BY DatabaseName, TableName",
     "round": "0s",
     "table": "columns"
    }
   ]
  },
  {
   "title": "Dictionaries Info Base",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "last_successful_update_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database DatabaseName,\n    name DictionnaryName,\n    status Status,\n    type Type,\n    bytes_allocated,\n    query_count,\n    element_count,\n    hit_rate,\n    load_factor\nFROM $table\n\nWHERE $timeFilter\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    CurrentMetric_MemoryTracking\nFROM system.metric_log\nWHERE event_date >= toDate(1609221187) AND event_time >= toDateTime(1609221187)\nORDER BY t",
     "round": "0s",
     "table": "dictionaries"
    }
   ]
  },
  { "title": "Top charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top $top request's rate by type: $type; user: $user; query type: $query_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "$rateColumns(\n    substring(query,  1,  45) AS query,\n    count() c)\nFROM $table\nWHERE\n    cityHash64(query) global in (\n    SELECT cityHash64(substring(query,  1,  45)) AS h\n    FROM $table\n    WHERE\n        $timeFilter\n        AND type in ($type)\n        AND initial_user in ($user)\n        AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\n    GROUP BY h\n    ORDER BY count() desc\n    LIMIT $top)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM (SELECT t, groupArray((query, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, substring(query, 1, 45) AS query, count() c FROM system.query_log\nWHERE event_date >= toDate(1603862271) AND event_time >= toDateTime(1603862271) AND\n    cityHash64(query) global in (\n    SELECT cityHash64(substring(query,  1,  45)) AS h\n    FROM system.query_log\n    WHERE\n        event_date >= toDate(1603862271) AND event_time >= toDateTime(1603862271)\n        AND type in (1,2,3,4)\n        AND initial_user in ('default')\n        AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\n    GROUP BY h\n    ORDER BY count() desc\n    LIMIT 30)\n    AND type in (1,2,3,4)\n    AND initial_user in ('default')\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY t, query ORDER BY t, query) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Types",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 19 },
   "content": "1 - successful start of query execution\n\n2 - successful end of query execution\n\n3 - exception before start of query execution\n\n4 - exception while query execution"
  },
  {
   "title": "Top slow queries by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY duration desc\nLIMIT $top",
     "rawQuery": "SELECT     rand() as t,     substring(query,  1,  70) AS query,     avg(query_duration_ms) duration,     count() count FROM system.query_log WHERE     event_date >= toDate(1498209947) AND event_time >= toDateTime(1498209947)     AND type in (1,2,3,4)     and initial_user in ('default')     and('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY query ORDER BY duration desc LIMIT 5",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top memory consumers by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    avg(memory_usage) usage,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT $top",
     "rawQuery": "SELECT     rand() as t,     substring(query,  1,  70) AS query,     avg(memory_usage) usage,     count() count FROM system.query_log WHERE     event_date >= toDate(1498209947) AND event_time >= toDateTime(1498209947)     AND type in (1,2,3,4)     and initial_user in ('default')     and('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY query ORDER BY usage desc LIMIT 5",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top failed queries by user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"darkorange\">type</font>,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"cornflowerblue\">3</font>,<font color=\"cornflowerblue\">4</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font><br />    query,<br />    <font color=\"darkorange\">type</font><br /><font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    type,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in (3,4)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY\n    query,\n    type\nORDER BY count desc\nLIMIT $top",
     "rawQuery": "SELECT     rand() as t,     substring(query,  1,  70) AS query,     type,     count() count FROM system.query_log WHERE     event_date >= toDate(1498209947) AND event_time >= toDateTime(1498209947)     AND type in (3,4)     and initial_user in ('default')     and('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY     query,     type ORDER BY count desc LIMIT 5",
     "table": "query_log"
    }
   ]
  },
  { "title": "Request charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Reqs/s by type: $type; user: $user; query type: $query_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "$rate(count() c)\nFROM $table\nwhere  type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_MergedRows) as ProfileEvent_MergedRows\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1609221193)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query duration by type: $type; user: $user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms)  select_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br />    <font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'select'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms)  select_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\n    and positionCaseInsensitive(query,  'select') = 1\n    and initial_user in ($user)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms)  select_duration\nFROM system.query_log\nWHERE\n    event_date >= toDate(1608193103) AND event_time >= toDateTime(1608193103)\n    AND type = 2\n    and positionCaseInsensitive(query,  'select') = 1\n    and initial_user in ('u_ops','default')\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) insert_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user in ($user)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) insert_duration\nFROM system.query_log\nWHERE\n    event_date >= toDate(1608193175) AND event_time >= toDateTime(1608193175)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user in ('u_ops','default')\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  { "title": "Query log table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Query log by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time as EventTime,\n    concat(substring(query,1,120), '...') Query,\n    if(exception!='', 'fail', 'success') Result,\n    user as Operator,\n    query_duration_ms as Duration,\n    memory_usage as Memory,\n    read_rows as ReadRows,\n    read_bytes as ReadBytes\nFROM $table\nWHERE $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nORDER BY EventTime DESC\nLIMIT 1000",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_MergedRows\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1608193667)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "TimeRange Top $top Slow Query Basic",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    event_time as EventTime,\n    substring(query, 1, 140) as Query,\n    user as Operator,\n    query_duration_ms as Duration,\n    read_rows as ReadRows,\n    read_bytes as ReadBytes\n\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY Duration DESC\n\nLIMIT $top\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_InsertedRows\nFROM system.metric_log\nWHERE event_date >= toDate(1608193246) AND event_time >= toDateTime(1608193246)\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "CPU Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toInt32(date_trunc('minute', toDateTime(event_time))) * 1000 as t,\n    avg(ProfileEvent_OSCPUWaitMicroseconds) as ProfileEvent_OSCPUWaitMicroseconds\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    toInt32(date_trunc('minute', toDateTime(event_time))) * 1000 as t,\n    avg(ProfileEvent_OSCPUWaitMicroseconds) as ProfileEvent_OSCPUWaitMicroseconds\nFROM system.metric_log\nWHERE event_date >= toDate(1616030910) AND event_time >= toDateTime(1616030910)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "IO Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_OSIOWaitMicroseconds) as ProfileEvent_OSIOWaitMicroseconds\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_MergedRows) as ProfileEvent_MergedRows\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1616059575)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Zookeeper Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_ZooKeeperWaitMicroseconds) as ProfileEvent_ZooKeeperWaitMicroseconds\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_FailedQuery) ProfileEvent_FailedQuery\nFROM system.metric_log\n\nWHERE event_date >= toDate(1609221214) AND event_time >= toDateTime(1609221214)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_MemoryTracking\nFROM $table\nWHERE $timeFilter\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    CurrentMetric_TCPConnection\nFROM system.metric_log\nWHERE event_date >= toDate(1608787421) AND event_time >= toDateTime(1608787421)\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_InsertedBytes) as ProfileEvent_InsertedBytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_InsertedBytes) as ProfileEvent_InsertedBytes\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608861376) AND event_time >= toDateTime(1608861376)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "row/s" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_InsertedRows) as ProfileEvent_InsertedRows\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_InsertedRows) as ProfileEvent_InsertedRows\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608861133) AND event_time >= toDateTime(1608861133)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Merged Uncompressed Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_MergedUncompressedBytes) as ProfileEvent_MergedUncompressedBytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    database as DatabaseName,\n    table as TableName,\n    count(1) as ColumnCnt\nFROM system.columns\nWHERE database!='system'\nGROUP BY DatabaseName, TableName",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Merged Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "rows/s" }
   ],
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_MergedRows) as ProfileEvent_MergedRows\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_MergedRows) as ProfileEvent_MergedRows\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1608707620)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "HTTP Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_HTTPConnection\nFROM $table\n\nWHERE $timeFilter\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    CurrentMetric_TCPConnection\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608021670) AND event_time >= toDateTime(1608021670)",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "TCP Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_TCPConnection\nFROM $table\nWHERE $timeFilter\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    CurrentMetric_TCPConnection\nFROM system.metric_log\nWHERE event_date >= toDate(1608113382) AND event_time >= toDateTime(1608113382)\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_Query) as ProfileEvent_Query\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_Query) as ProfileEvent_Query\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608707645) AND event_time >= toDateTime(1608707645)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Failed QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_FailedQuery) ProfileEvent_FailedQuery\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(concat(substr(toString(event_time), 1, 16), ':00'))), 2) * 2) * 1000 as t,\n    avg(ProfileEvent_FailedQuery) ProfileEvent_FailedQuery\nFROM system.metric_log\n\nWHERE event_date >= toDate(1609221227) AND event_time >= toDateTime(1609221227)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  }
 ]
}