version: '3'
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.3.13.6
    restart: always
    ports:
      - 8123:8123  # http
      - 9000:9000  # native protocol
      - 9363:9363  # metrics server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./config_files/clickhouse/etc/clickhouse-server:/etc/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    
volumes:
  clickhouse-data:
  clickhouse-logs:

