version: '3'
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.3.13.6
    restart: always
    ports:
      - 8123:8123  # http
      - 9000:9000  # native protocol
      - 9363:9363  # metrics server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./config_files/clickhouse/etc/clickhouse-server:/etc/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.9
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./config_files/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    container_name: grafana
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    
volumes:
  clickhouse-data:
  clickhouse-logs:
  prometheus_data:
  grafana_data:

