version: '3'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.8
    restart: always
    ports:
      - 8123:8123  # http
      - 9000:9000  # native protocol
      - 9363:9363  # metrics server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./config_files/clickhouse/etc/clickhouse-server:/etc/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - minio
      - minio-bucket-creator

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.9
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./config_files/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - minio-prometheus-monitoring-cluster
      - minio-prometheus-monitoring-node
      - minio-prometheus-monitoring-bucket

  grafana:
    container_name: grafana
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config_files/grafana/etc/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./config_files/grafana/etc/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./config_files/grafana/var/lib/grafana/dashboards/:/var/lib/grafana/dashboards/
      # uncomment the following line, if you don't have access to grafana.com plugins and download a plugin manually (read README.md file)
      - ./config_files/grafana/var/lib/grafana/plugins/:/var/lib/grafana/plugins/
    depends_on:
      - prometheus
    
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    restart: always
    env_file:
      - .env
    ports:
      - 9001:9001
      - 9002:9002
    volumes:
      - minio_data:/var/lib/minio/data
    command: minio server /var/lib/minio/data --address 0.0.0.0:9002 --console-address ":9001"

  minio-bucket-creator:
    container_name: minio-bucket-creator
    image: minio/mc:RELEASE.2023-09-13T23-08-58Z
    env_file:
      - .env
    entrypoint: >
      /bin/bash -c "
      /usr/bin/mc alias set myminio http://minio:9002 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/${MINIO_CLICKHOUSE_BACKUP_BUCKET:-clickhouse};
      /usr/bin/mc anonymous set public myminio/${MINIO_CLICKHOUSE_BACKUP_BUCKET:-clickhouse};
      exit 0;
      "
    depends_on:
      - minio
  
  minio-prometheus-monitoring-cluster:
    container_name: minio-prometheus-monitoring-cluster
    image: minio/mc:RELEASE.2023-09-13T23-08-58Z
    env_file:
      - .env
    volumes:
      - ./config_files/prometheus/prometheus.yaml:/home/prometheus.yaml
    entrypoint: >
      /bin/bash -c "
      /usr/bin/mc alias set myminio http://minio:9002 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD > /dev/null;
      /usr/bin/mc admin prometheus generate myminio cluster | sed '1d' | awk '{print \"  \" $0}' >> /home/prometheus.yaml;
      "
    depends_on:
      - minio
  
  minio-prometheus-monitoring-node:
    container_name: minio-prometheus-monitoring-node
    image: minio/mc:RELEASE.2023-09-13T23-08-58Z
    env_file:
      - .env
    volumes:
      - ./config_files/prometheus/prometheus.yaml:/home/prometheus.yaml
    entrypoint: >
      /bin/bash -c "
      /usr/bin/mc alias set myminio http://minio:9002 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD > /dev/null;
      /usr/bin/mc admin prometheus generate myminio node | sed '1d' | awk '{print \"  \" $0}' >> /home/prometheus.yaml;
      "
    depends_on:
      - minio

  minio-prometheus-monitoring-bucket:
    container_name: minio-prometheus-monitoring-bucket
    image: minio/mc:RELEASE.2023-09-13T23-08-58Z
    env_file:
      - .env
    volumes:
      - ./config_files/prometheus/prometheus.yaml:/home/prometheus.yaml
    entrypoint: >
      /bin/bash -c "
      /usr/bin/mc alias set myminio http://minio:9002 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD > /dev/null;
      /usr/bin/mc admin prometheus generate myminio bucket | sed '1d' | awk '{print \"  \" $0}' >> /home/prometheus.yaml;
      "
    depends_on:
      - minio

volumes:
  clickhouse-data:
  clickhouse-logs:
  prometheus_data:
  grafana_data:
  minio_data:
